[project]
name = "document-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.14.4",
    "pytest>=8.3.4",
    "pre-commit>=4.0.1",
    "pytest-cov>=7.0.0",
]

[tool.ruff]
extend-exclude = ["*.ipynb"]
